name: Docker Image CI

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
    
env:
  test: 1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install RPM & Pacman (on Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update &&
        sudo apt-get install --no-install-recommends -y rpm &&
        sudo apt-get install --no-install-recommends -y libarchive-tools &&
        sudo apt-get install --no-install-recommends -y libopenjp2-tools
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3  # 抽取项目信息，主要是镜像的tag
      with:
        images: issuperman/yesplaymusic

    - name: Build and push Docker image
      uses: docker/build-push-action@v2 # docker build & push
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
    - name: Push notification
      run: |
         curl -sX POST "${{ secrets.BARKURL }}/${{ secrets.BARKKEY }}" -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' -d 'title=Action%20Status&body=YesPlayMusic%20-%20docker%20build%20success!&group=GithubAction&icon=https://github.com/isSuperman/WrtFactory/blob/15f2afc79edd2340f46f87d415e6fc3bfae56930/images/barkGroupLogo.jpeg?raw=true'

